;LAB_2
;PROBLEM 2: WRITE AN 8086 ASSEMBLY PROGRAM TO 
;1. PROMPT THE USER
;2. READ FIRST, MIDDLE, LAST OF INITIALS OF THE PERSON'S NAME
;3. DISPLAY THEM ON THE LEFT MARGIN OF THE NEXT LINE

.MODEL SMALL
.STACK 100H
.DATA
MSG DB "ENTER THREE INITIALS: $"
FU DB 0DH, 0AH
INI1 DB ?, 0DH, 0AH
INI2 DB ?, 0DH, 0AH
INI3 DB ?, "$"

.CODE 
MAIN PROC
    MOV AX, @DATA
    MOV DS, AX
    
    
    LEA DX, MSG
    MOV AH, 09
    INT 21H
    
    MOV AH, 01
    INT 21H
    MOV INI1, AL
    INT 21H
    MOV INI2, AL
    INT 21H
    MOV INI3, AL
    
    LEA DX, FU
    MOV AH, 09
    INT 21H
    
    MOV AH, 4CH
    INT 21H    